title: CV Website
description: Personal CV website built with cvless Jekyll theme
baseurl: ""
url: https://omertekin2002.github.io

theme: cvless

# site settings
taglong: Personal CV website built with cvless Jekyll theme
tagshort: CV Website
cv: true

# author settings
author:
  name: Your Name
  email: your.email@example.com
photo: assets/files/photo.jpg
joblines:
  - Your Position
  - Your Company/Institution
  - Your Location
address: Your Address
phone: +1 234 567 890

# profile links
profile:
  facebook: https://www.facebook.com/yourusername
  x: https://x.com/yourusername
  mastodon: https://mastodon.social/@yourusername
  bluesky: https://bsky.app/profile/yourusername.bsky.social
  instagram: https://www.instagram.com/yourusername
  linkedin: https://www.linkedin.com/in/yourusername
  xing: https://www.xing.com/profile/yourusername
  stackoverflow: https://stackoverflow.com/users/0000000/yourusername
  medium: https://medium.com/@yourusername
  github: https://github.com/yourusername

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never 