# Site settings

title: "Your Name"
email: your.email@example.com
description: >-
  A short description of your CV.
baseurl: ""
url: "https://example.com"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Only include pages explicitly listed here in the navigation.
# An empty array hides all pages from the top navigation bar.
header_pages:
  - index.md

# Social links
github_username: your-github-username
linkedin_username: your-linkedin-username
