# Site settings

title: "Ömer Tekin"
email: omertekin2002@hotmail.com
description: >-
  Hello
baseurl: ""
url: "https://omertekin2002.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social links
github_username: omertekin2002
linkedin_username: ömer-tekin
