# Site settings

title: "Ömer Tekin"
email: omertekin2002@hotmail.com
description: >-
  Hello
baseurl: ""
url: "https://example.com"

# Build settings
markdown: kramdown
theme: jekyll-theme-dinky
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social links
github_username: omertekin2002
linkedin_username: ömer-tekin
