# Site settings

title: "Your Name"
email: your.email@example.com
description: >-
  A short description of your CV.
baseurl: ""
url: "https://example.com"

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social links
github_username: your-github-username
linkedin_username: your-linkedin-username
