# Site settings

title: "Ömer Tekin"
email: omertekin2002@hotmail.com
description: >-
  Law student focused on international arbitration and business. Experienced at Çakmak, Bezen, DNPartners. Skilled in Power BI, SQL, Python. Open to opportunities.
baseurl: ""
url: "https://omertekin2002.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social links
github_username: omertekin2002
linkedin_username: ömer-tekin
